version: '{build}'
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: cmake -DBOOST_ROOT=C:\Libraries\boost_1_66_0 -DBoost_USE_STATIC_LIBS=ON -DENABLE_MYSQL=OFF .
build:
  project: trojan.sln
  parallel: true
  verbosity: minimal
test: off
deploy: off
